apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtdeployment
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      replicas: 3
      containers:
      - name: nginxcontainer
        image: melihselamiurkmez/dtcloud
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 8080
    targetPort: 80
